// Code generated by mockery v2.1.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MqttInterface is an autogenerated mock type for the MqttInterface type
type MqttInterface struct {
	mock.Mock
}

// Listen provides a mock function with given fields: _a0, _a1
func (_m *MqttInterface) Listen(_a0 string, _a1 *[]string) {
	_m.Called(_a0, _a1)
}

// Publish provides a mock function with given fields: _a0, _a1
func (_m *MqttInterface) Publish(_a0 string, _a1 string) {
	_m.Called(_a0, _a1)
}
